---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: service-controller-secrets
  namespace: service-controller
spec:
  encryptedData:
    SERVICE_CONTROLLER_DB_PASSWORD: AgCUgvElpKVtytfKAbNg6gW7E9jljhbCUNaXgTyh/ibw2HFR2IfbPrhj5R2GHuTGsTioe3t2jTGc0xV/xi5Jhfeie7nd9EVvrJ8x0aCTzjbmQ6xxHAPIZt07eYiEKJ7RSihELRRi1Tz+V0eXpdQiV8SXHMzMwdtBXXZfRcJoQuu0Sr8C6iq2L+0L7HXxgoOiLmLuuAw3aFmHdEqXXJP0vOKt1x64sfUq/eOw+U23Iunlw1GYGiwRtqLx3dnXcwoQA/xsuTYrmgBQqmzpVzoOIHvLXrBR9Ebik1s+qP+ehdbReXTdd4EOZ4DhCWUvBVhwP9sTnnz6MDeHqnVlVFTXpxS4OHHf4x4mb4LInkbsat+LIBKf7q1DjItfMhZxoIjGwob59/waCkYNNuKKCKHJbyDaSXR/tfUShpihEdWIZKdWlwpD2gHwE+TI3uFtPH5Pl1m6tWDUBm4g5/urWOUcJ6IGes6bzLQewYLNEcbuNN/+P8qjhzZFlIv4xrN74Vg8N7TCC6FOU/sxOaQMIZTAqVMv8sLFiZKYvDWcE6yCI6I8McLKtkHypzU5Cw5U0zvzGuV2DE+xiLIDwskyXSiuuXG+7rO2eFcWAcXzIerqVo53PGe3ganp20aVb5aRBeljjU/zanwU1x6A7q6lQ7HjFktYKJ44e+H4C7i1+7bIsfRIrauUFQGilic/ji7VoE1SL6jmVvpSjmIJyuvOeYGJkh6Q931n/AAs2wIQezze
  template:
    metadata:
      name: service-controller-secrets
      namespace: service-controller
